apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duckdb.fullname" . }}
  labels:
    {{- include "duckdb.labels" . | nindent 4 }}
data:
  duckdbrc: |
    {{- if .Values.duckdb.extensions }}
    {{- range .Values.duckdb.extensions }}
    INSTALL {{ . }};
    LOAD {{ . }};
    {{- end }}
    {{- end }}
    
    .open {{ .Values.persistence.path }}/{{ .Values.duckdb.databaseFile }}
    
    {{- if .Values.duckdb.config.memory_limit }}
    SET memory_limit='{{ .Values.duckdb.config.memory_limit }}';
    {{- end }}
    {{- if .Values.duckdb.config.threads }}
    SET threads={{ .Values.duckdb.config.threads }};
    {{- end }}
    
    {{- if .Values.configMap.additionalConfig }}
    {{ .Values.configMap.additionalConfig }}
    {{- end }}
    
    .timer on
    
    .mode table
    
    SELECT name, loaded FROM duckdb_extensions() WHERE loaded = true;
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;
            location / {
                proxy_pass http://127.0.0.1:{{ .Values.service.port }};
            }
        }
    }
